services:
  backend:
    build: .
    container_name: pharmacy-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - pharmacy-network

  db:
    image: mysql:8.0
    container_name: pharmacy-db
    environment:
      MYSQL_ROOT_PASSWORD: meds
      MYSQL_DATABASE: pharmacy
    ports:
      - "3306:3306"
    volumes:
      - pharmacy-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pharmacy-network

volumes:
  pharmacy-data:

networks:
  pharmacy-network:
    driver: bridge