services:
  backend:
    build: .
    container_name: pharmacy-backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - pharmacy-network

  db:
    image: mysql:8.0
    container_name: pharmacy-db
    environment:
      MYSQL_ROOT_PASSWORD: meds
      MYSQL_DATABASE: pharmacy
    ports:
      - "3306:3306"
    volumes:
      - pharmacy-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pharmacy-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pmeds"]
      timeout: 5s
      retries: 30
      interval: 5s
      start_period: 30s

volumes:
  pharmacy-data:

networks:
  pharmacy-network:
    driver: bridge